# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true
mathjax: true

# Sidebar
sidebar: bottom
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- links

# Links
links:
  Dev Note: http://note.49px.com

# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins: 
fb_app_id:

# Duoshuo
duoshuo_shortname: smilingpoplar

# Baidu share
baidushare: